language: ruby
cache: bundler
rvm:
  - &latest_ruby 2.7
  - 2.3
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  matrix:
    - JEKYLL_VERSION="~> 3.8"
matrix:
  include:
    - rvm: *latest_ruby
      env: JEKYLL_VERSION="~> 3.8.6"
    - rvm: *latest_ruby
      env: JEKYLL_VERSION=">= 4.0.0"
before_install:
  - gem update --system
  - gem install bundler
before_script: bundle update
script: script/cibuild
notifications:
  email: false
